### ISSUE TITLE
Documentation is out of date - references version 0.0.2

### ISSUE THREAD

**Issue by adrianyorke** [MarketSquare/robotframework-aws#11]
The documentation [here](https://teaglebuilt.github.io/robotframework-aws/) is for version 0.0.2.   There are missing keywords, for example `Delete File` or `Create Session With Profile`.

**Comment by NeoMorfeo** [comment]
The link doesn't even work, is there any way to generate the documentation locally?

**Comment by adrianyorke** [comment]
The domain was changed to all lower case in line with other Robot Framework libraries, hence broken link.  I've updated my comment to reflect the new domain name and confirm the link is now working.

**Comment by adrianyorke** [comment]
> The link doesn't even work, is there any way to generate the documentation locally?

The domain was changed to all lower case in line with other Robot Framework libraries, hence broken link. I've updated my comment to reflect the new domain name and confirm the link is now working.

At the bottom of the documentation page there is this "Generated by Libdoc on 2019-08-17 13:02:36."  Libdoc is a Robot Framework tool.  You can read more about it [here](https://robotframework.org/robotframework/2.1.2/tools/libdoc.html).
