### ISSUE TITLE
Inconsistencies with versioning

### ISSUE THREAD

**Issue by adrianyorke** [MarketSquare/robotframework-aws#14]
version.py reports the following:
VERSION = '0.0.2'

pypi reports:
robotframework-aws 0.0.4
Last released: Oct 4, 2019

Documentation references 0.0.2 which also causes confusion reported here: https://github.com/teaglebuilt/robotframework-AWS/issues/11

I suggest everything is synchronized. Perhaps we target a new release 0.0.5 with all current issues closed?

**Comment by adrianyorke** [comment]
Also, how does versioning work on this project?  Should we increment the version number when we submit PRs or do repo admins want to handle this perhaps?

**Comment by teaglebuilt** [comment]
> Also, how does versioning work on this project? Should we increment the version number when we submit PRs or do repo admins want to handle this perhaps?

well my thought was that travis ci would deploy to pypi on tags, every time  we increment version. So ive seen some projects set goals and when the goals are reached. 0.0.4 -> 0.0.5

If this project has contributors then i think a version bump would work every time a pull request is merged with a new tag release. 

@adrianyorke  what do you think?

**Comment by adrianyorke** [comment]
Sounds workable.   It's not my specialty but agreeing when/how to increment the version number seems sensible.   Perhaps not so critical at this stage but later on it needs to be well defined so there is no confusion.
