### ISSUE TITLE
github repository name uses mixed case, different to pypi.org registration

### ISSUE THREAD

**Issue by adrianyorke** [MarketSquare/robotframework-aws#16]
Looking at other popular RF libraries (github repos), it seems to be more common to use only lower case lettering for library/repo name.

For example:
- robotframework/robotframework
- robotframework-jsonlibrary
- robotframework-requests
- robotframework-httplibrary
- robotframework-jsonlibrary
- robotframework-djangolibrary

Also, the pypi registration for this library is "robotframework-aws" and the instructions suggest using "pip install robotframework-aws" to import the library.

My suggestion is to rename the library (and github repo) to "robotframework-aws" so we are consistent everywhere.

**Comment by teaglebuilt** [comment]
Your right, I just changed the name on the repository. Pypi is already the correct casing with the correct instructions

https://pypi.org/project/robotframework-aws/

**Comment by adrianyorke** [comment]
Thanks, looks good and consistent everywhere now so there won't be any confusion.
