### ISSUE TITLE
add tests for keywords

### ISSUE THREAD

**Issue by teaglebuilt** [MarketSquare/robotframework-aws#19]
We need to cover existing keywords with unit tests. Adleast, every keyword should have a direct unit test. We also need solutions in how we will choose to write our tests with aws services, mocking, etc...

**Comment by adrianyorke** [comment]
Yes, I agree.  I will have a think about this next time I am deep into coding/testing.

**Comment by adrianyorke** [comment]
I'm still  pondering this.  Unit tests should not have any external dependencies, i.e. they should be able to test the code in isolation without connecting to external systems but of course the whole point of this library is to connect to AWS.

**Comment by teaglebuilt** [comment]
> I'm still pondering this. Unit tests should not have any external dependencies, i.e. they should be able to test the code in isolation without connecting to external systems but of course the whole point of this library is to connect to AWS.

yeah since this library is essentially a wrapper. Each keyword needs tests to verify the functionality.
