### ISSUE TITLE
Extend session configuration

### ISSUE THREAD

**Issue by EgorOs** [MarketSquare/robotframework-aws#21]
I was using this library and ran into an issue when I needed to pass aws_session_token in addition to aws_access_key and aws_secret_key. Maybe it would be a good idea to add [all possible boto3 session parameters](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html) to '[Create Session With Keys](https://github.com/teaglebuilt/robotframework-aws/blob/master/src/AWSLibrary/keywords/session.py#L14)' keyword?

**Comment by teaglebuilt** [comment]
i agree. I think something else that needs to be looked into as well is the possibility to pull credentials from ~/.aws/credentials or config....

For now, all possible parameters will be added.

**Comment by EgorOs** [comment]
Thank you,
In our case we create session with aws access key, secret key and session token, which are passed into jenkins job as environmental variables via [credentials plugin](https://jenkins.io/doc/pipeline/steps/credentials-binding/#withcredentials-bind-credentials-to-variables). So it is a kind of a case, when a bit more flexibility is required.

Also I could take this issue

**Comment by adrianyorke** [comment]
Is this issue still open?  @teaglebuilt : EgorOs was offering to submit PR - ok with you?

**Comment by adrianyorke** [comment]
@teaglebuilt : how about this one?  @EgorOs ws offering to take this issue or did you have it in progress already?  Perhaps we should agree which version of boto3 we are aligning with although I don't think the session parameters change so often.

**Comment by mrkmcnamee** [comment]
Hi,

we have a use case where we run Robot in an ECS Task as part of the deployment of our services to an ECS Cluster. This would use role-based authentication to access AWS services. In other words, this doesn't require access keys. So I would really like to have `Get Session With Role` Keyword.

Much appreciated,
Kevin
