### ISSUE TITLE
RF fails to import test library 'AWSLibrary'

### ISSUE THREAD

**Issue by mayurpande** [MarketSquare/robotframework-aws#31]
I am unable to load it in, says there are errors with 
`from AWSLibrary.base import DynamicCore`
and 
`from .exceptions import KeywordError, ContinuableError, FatalError`

Does it work with Python2.7?

**Comment by adrianyorke** [comment]
According to PyPi the lib depends on Python Version 3.7:
https://pypi.org/project/robotframework-aws/
