### ISSUE TITLE
Keyword request: Get Session With Role 

### ISSUE THREAD

**Issue by mrkmcnamee** [MarketSquare/robotframework-aws#54]
Hi,

we have a use case where we run Robot in an ECS Task as part of the deployment of our services to an ECS Cluster. This would use role-based authentication to access AWS services. In other words, this doesn't require access keys. So I would really like to have` Get Session With Role` keyword.

Much appreciated,
Kevin

**Comment by mrkmcnamee** [comment]
Something like this:
```python
    @keyword('Create Session With Role')
    def create_session_with_role(self, region):
        """ Create an AWS session in region using current role context.

        | =Arguments= | =Description= |
        | ``region`` | <str> The AWS region name. |

        *Examples:*
        | Create Session With Role | eu-west-1 |
        """
        session = boto3.Session(region_name=region)
        logger.info(f"Session created: {str(session)} using current role context")
        self._cache.register(session, alias=region)
        self.library.session = session
        return session
```

**Comment by samuelpcabral** [comment]
Sure! I can do it soon in the next version...

**Comment by samuelpcabral** [comment]
Hi @mrkmcnamee I added your keyword in version 0.2.0 
pip install robotframework-aws==0.2.0
