### ISSUE TITLE
Please confirm license

### ISSUE THREAD

**Issue by adrianyorke** [MarketSquare/robotframework-aws#7]
Thanks for the library, looks great!  I might be able to help by adding more useful RF keywords via pull requests.

One issue that's blocking us using this library is that the licensing may be too prohibitive.

LICENSE file in the code reports:
**GNU Affero General Public License v3.0**

On PyPi it is listed as:
**MIT License (MIT)**

Please confirm which license model you are using.

Thanks

**Comment by teaglebuilt** [comment]
Thankyou! I had no idea, I will change it immediately. Ive been in between different projects and this might explain the lack of visibility. Ill be changing it shortly.

**Comment by teaglebuilt** [comment]
Confirm BSD License. will change in Pypi shortly

**Comment by adrianyorke** [comment]
License has now been updated to MIT which matches PyPi.  I will close this issue now, thanks.
